#!/bin/bash
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'


echo -e "\n${BLUE}Start Prettier format...${NC}\n"
npm run format

echo -e "\n${BLUE}Start Stylelint format...${NC}\n"
npm run lint:styles

echo -e "\n${BLUE}Start ESlint...${NC}\n"
npm run lint

echo -e "\n${GREEN}Pre-commit done${NC}\n"